### ISSUE TITLE
Support 'table_prefix'

### ISSUE THREAD

**Issue by acarter24** [storebrand/target-mssql#24]
It is possible to support something like `table_prefix`?

I would like to collect multiple tap streams under a single database schema, prefixing each table with `${MELTANO_EXTRACTOR_NAMESPACE}` to give a bit more order / ease of filtering.

https://hub.meltano.com/loaders/target-bigquery--adswerve/#table_prefix-setting

**Comment by hholgersen** [comment]
Yes, that should be doable - I am not entirely sure how/where it is best to implement it, so I need to do some research first.

**Comment by acarter24** [comment]
Great. I would be happy to attempt a PR with a little guidance, I am experienced in python but less so in the world of singer taps/targets.

**Comment by hholgersen** [comment]
@acarter24 I have added a table_prefix config in a new branch: https://github.com/storebrand/target-mssql/tree/table_prefix.

It passes my unit tests, are you able to give it a real test before I merge it to main?

**Comment by acarter24** [comment]
Looks perfect!

![image](https://user-images.githubusercontent.com/126154605/233038113-5e248f67-560d-43d4-b1cb-450fa7df5a12.png)

```yaml
  - name: target-mssql
    variant: storebrand
    pip_url: git+https://github.com/storebrand/target-mssql.git@table_prefix
    config:
      username: ${SYSTEM_DB_USER}
      password: ${SYSTEM_DB_PASS}
      host: ${SYSTEM_DB_IP}
      port: ${SYSTEM_DB_PORT}
      database: dwh_${MELTANO_ENVIRONMENT}
      default_target_schema: meltano
      table_prefix: '${MELTANO_EXTRACTOR_NAMESPACE}_'
```
